version = 0.1

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "github-app-token"
role_arn = "arn:aws:iam::978218332026:role/github-app-token-cfn-service-role-us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1f2z7dd66gmx0"
s3_prefix = "github-app-token"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiUrl=\"https://api.github.com\""

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "github-app-token"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wkrhx2ap1xpk"
s3_prefix = "github-app-token"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiUrl=\"https://api.github.com\" AppId=\"/github-app-token/app-id\" PrivateKey=\"/github-app-token/private-key\""
image_repositories = []
